package edu.co.unbosque.compiladores.interprete.parser;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------


/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IT = 11;
  public static final int IS = 10;
  public static final int CP = 21;
  public static final int LS = 14;
  public static final int OT = 7;
  public static final int OS = 6;
  public static final int LP = 15;
  public static final int OP = 20;
  public static final int IN = 12;
  public static final int LN = 16;
  public static final int ON = 8;
  public static final int O = 5;
  public static final int M = 2;
  public static final int COLON = 25;
  public static final int L = 13;
  public static final int M_TYPE = 23;
  public static final int CB = 19;
  public static final int MT = 3;
  public static final int I = 9;
  public static final int OB = 18;
  public static final int TYPE = 22;
  public static final int STRING = 17;
  public static final int COMMA = 24;
  public static final int MN = 4;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "M",
  "MT",
  "MN",
  "O",
  "OS",
  "OT",
  "ON",
  "I",
  "IS",
  "IT",
  "IN",
  "L",
  "LS",
  "LP",
  "LN",
  "STRING",
  "OB",
  "CB",
  "OP",
  "CP",
  "TYPE",
  "M_TYPE",
  "COMMA",
  "COLON",
  "NUMBER"
  };
}

